services:
  postgres:
    container_name: du_postgres
    image: postgres
    environment:
      POSTGRES_USER: duhacks
      POSTGRES_PASSWORD: Mr.VivekThumar@2004
      PGDATA: /var/lib/postgresql/data
    ports:
      - 5432:5432