spring:
  application:
    name: duhacksbackend
  datasource:
    driver-class-name: org.postgresql.Driver
    username: duhacks
    password: Mr.VivekThumar@2004
    url: jdbc:postgresql://localhost:5432/duhacks
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: darkdark2189@gmail.com
    password: ppofakoutvdyrffg
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8888